name: VillagerMarket
main: net.bestemor.villagermarket.VMPlugin
version: 1.13.2

author: Bestem0r
description: Bestem0r tarafindan yapilmis Villager Shop olusturma plugini
api-version: 1.13
folia-supported: true
depend: [ Vault ]
softdepend:
  - Essentials
  - CMI
  - WorldEdit
  - WorldGuard
  - LightEconomy
  - TheNewEconomy
  - HellConomy
  - EasyConomy
  - PlaceholderAPI
  - Citizens
  - Towny
  - NBTApi
  - Lands
  - UltraEconomy
commands:
  vm:
    description: Tum Villager Market komutlarini listeler
    usage: /vm help
    aliases:
      - villagermarket
  shop:
    description: Varsayilan yonetici dukkanini acar
    usage: /shop

permissions:
  villagermarket.command.shop:
    default: op
    description: Varsayilan yonetici dukkanini acar
  villagermarket.admin:
    default: op
    description: Tum VillagerMarket izinleri
    children:
      villagermarket.adminshops: true
      villagermarket.command.create: true
      villagermarket.command.item: true
      villagermarket.command.search: true
      villagermarket.command.stats: true
      villagermarket.command.remove: true
      villagermarket.command.move: true
      villagermarket.command.reload: true
      villagermarket.command.expiredstorage: true
      villagermarket.spy: true
      villagermarket.rename: true
      villagermarket.use_spawn_item: true
      villagermarket.unlimited_shops: true
      villagermarket.command.help: true
      villagermarket.command.getid: true
      villagermarket.use_citizens: true
      villagermarket.set_trade_type: true

  villagermarket.adminshops:
    default: op
    description: Yonetici dukkanlarini duzenler
  villagermarket.command.create:
    default: op
    description: Villager Shop olusturur
  villagermarket.command.item:
    default: op
    description: Diger oyunculara Villager Shop esyasi verir
  villagermarket.command.search:
    default: op
    description: Yakindaki Villager Shoplari arar
  villagermarket.command.stats:
    default: op
    description: Villager Shop istatistiklerini gosterir
  villagermarket.command.remove:
    default: op
    description: Villager Shoplari kaldirir
  villagermarket.command.move:
    default: op
    description: Villager Shoplari tasir
  villagermarket.command.reload:
    default: op
    description: Villager Market'i yeniden yukler
  villagermarket.command.help:
    default: op
    description: Tum Villager Market komutlari
  villagermarket.command.expiredstorage:
    default: op
    description: Suresi dolmus depoyu acar
  villagermarket.command.getid:
    default: op
    description: Dukkan kimligini gosterir
  villagermarket.spy:
    default: op
    description: Diger oyuncularin dukkan duzenleyicilerini acar
  villagermarket.change_name:
    default: op
    description: Dukkan adini degistirir
  villagermarket.use_spawn_item:
    default: op
    description: Dukkan spawn esyasini kullanir
  villagermarket.unlimited_shops:
    default: op
    description: Sinirsiz dukkan
  villagermarket.max_shops.<amount>:
    default: op
    description: Maksimum dukkan sayisini ayarlar
  villagermarket.use_citizens:
    default: op
    description: Dukkanini NPC'ye donusturur
  villagermarket.bypass_limit:
    default: op
    description: Yonetici dukkan limitlerini asar
  villagermarket.bypass_price:
    default: op
    description: Maksimum fiyat sinirini asar
  villagermarket.bypass_max_rent:
    default: op
    description: Maksimum kira suresini asar
  villagermarket.set_trade_type:
    default: op
    description: Esya karsiligi takas modunu kullanmaya izin verir
